from datetime import datetime

from fastapi import HTTPException
from sqlalchemy.orm import Session

from backend.models import CustomerQuoteRequest, Product
from backend.schemas import (
    CandidatePriceRequest,
    CandidatePriceResponse,
    CustomerQuoteCandidatePriceRequest,
    CustomerQuoteRequestCreate,
    CustomerQuoteRequestResponse,
    CustomerQuoteRequestStatusUpdate,
    CustomerQuoteRequestUpdate,
    QuotePreviewRequest,
    QuotePreviewResponse,
)
from backend.services.candidate_price_service import generate_candidate_prices
from backend.services.quote_preview_service import calculate_quote_preview


WORKFLOW_NOTES = [
    "Customer quote request created.",
    "No price was generated by AI.",
    "This request does not approve or activate a price.",
]
ALLOWED_STATUSES = {"new", "reviewing", "quoted", "closed", "cancelled"}


def create_customer_quote_request(
    db: Session, payload: CustomerQuoteRequestCreate
) -> CustomerQuoteRequestResponse:
    _validate_quantity(payload.quantity)
    product = db.get(Product, payload.product_id)
    if product is None:
        raise HTTPException(status_code=404, detail="Product not found")
    request = CustomerQuoteRequest(
        customer_name=payload.customer_name,
        customer_email=payload.customer_email,
        customer_company=payload.customer_company,
        product_id=product.id,
        quantity=payload.quantity,
        requested_due_date=payload.requested_due_date,
        request_note=payload.request_note,
        status="new",
    )
    db.add(request)
    db.commit()
    db.refresh(request)
    return _to_response(request)


def list_customer_quote_requests(db: Session) -> list[CustomerQuoteRequestResponse]:
    requests = db.query(CustomerQuoteRequest).order_by(CustomerQuoteRequest.id.desc()).all()
    return [_to_response(request) for request in requests]


def get_customer_quote_request(
    db: Session, request_id: int
) -> CustomerQuoteRequestResponse:
    return _to_response(_get_model(db, request_id))


def update_customer_quote_request(
    db: Session, request_id: int, payload: CustomerQuoteRequestUpdate
) -> CustomerQuoteRequestResponse:
    request = _get_model(db, request_id)
    updates = payload.model_dump(exclude_unset=True)
    if "quantity" in updates:
        _validate_quantity(updates["quantity"])
    for key, value in updates.items():
        setattr(request, key, value)
    request.updated_at = datetime.utcnow()
    db.commit()
    db.refresh(request)
    return _to_response(request)


def update_customer_quote_request_status(
    db: Session, request_id: int, payload: CustomerQuoteRequestStatusUpdate
) -> CustomerQuoteRequestResponse:
    request = _get_model(db, request_id)
    if payload.status not in ALLOWED_STATUSES:
        raise HTTPException(status_code=400, detail="Unsupported status")
    request.status = payload.status
    if payload.assigned_to_username is not None:
        request.assigned_to_username = payload.assigned_to_username
    if payload.internal_note is not None:
        request.internal_note = payload.internal_note
    if payload.status == "reviewing":
        request.reviewed_at = datetime.utcnow()
    request.updated_at = datetime.utcnow()
    db.commit()
    db.refresh(request)
    return _to_response(request)


def quote_preview_from_request(db: Session, request_id: int) -> QuotePreviewResponse:
    request = _get_model(db, request_id)
    return calculate_quote_preview(
        db,
        QuotePreviewRequest(product_id=request.product_id, quantity=request.quantity),
    )


def candidate_prices_from_request(
    db: Session, request_id: int, payload: CustomerQuoteCandidatePriceRequest
) -> CandidatePriceResponse:
    request = _get_model(db, request_id)
    return generate_candidate_prices(
        db,
        CandidatePriceRequest(
            product_id=request.product_id,
            quantity=request.quantity,
            margin_rates=payload.margin_rates,
            include_competitor_context=payload.include_competitor_context,
        ),
    )


def _get_model(db: Session, request_id: int) -> CustomerQuoteRequest:
    request = db.get(CustomerQuoteRequest, request_id)
    if request is None:
        raise HTTPException(status_code=404, detail="Customer quote request not found")
    return request


def _validate_quantity(quantity: int) -> None:
    if quantity <= 0:
        raise HTTPException(status_code=400, detail="Quantity must be greater than 0")


def _to_response(request: CustomerQuoteRequest) -> CustomerQuoteRequestResponse:
    return CustomerQuoteRequestResponse(
        id=request.id,
        customer_name=request.customer_name,
        customer_email=request.customer_email,
        customer_company=request.customer_company,
        product_id=request.product_id,
        product_name=request.product.name,
        quantity=request.quantity,
        requested_due_date=request.requested_due_date,
        request_note=request.request_note,
        status=request.status,
        assigned_to_username=request.assigned_to_username,
        internal_note=request.internal_note,
        created_at=request.created_at,
        updated_at=request.updated_at,
        reviewed_at=request.reviewed_at,
        workflow_notes=WORKFLOW_NOTES,
    )
