from datetime import datetime

from sqlalchemy.orm import Session

from backend.db import SessionLocal
from backend.models import (
    Competitor,
    CompetitorPrice,
    CostProfile,
    PriceTable,
    PriceTableItem,
    Product,
)


DEMO_PRODUCTS = [
    {
        "name": "Demo A3 Flyer",
        "sku": "DEMO-A3-FLYER",
        "category": "A3 Flyer",
        "description": "Demo-only A3 flyer product for local MVP testing.",
    },
    {
        "name": "Demo Product / Brand Sticker",
        "sku": "DEMO-BRAND-STICKER",
        "category": "Product / Brand Sticker",
        "description": "Demo-only sticker product for local MVP testing.",
    },
]

DEMO_COMPETITORS = [
    {
        "name": "Demo Local Print Shop",
        "channel": "local_shop",
        "notes": "Demo reference only. Not real market data.",
    },
    {
        "name": "Demo Similar-Size Studio",
        "channel": "similar_size",
        "notes": "Demo reference only. Not real market data.",
    },
]


def seed_demo_data() -> None:
    db = SessionLocal()
    try:
        _seed_demo_data(db)
        db.commit()
    finally:
        db.close()


def _seed_demo_data(db: Session) -> None:
    products: dict[str, Product] = {}
    for product_data in DEMO_PRODUCTS:
        product = db.query(Product).filter(Product.sku == product_data["sku"]).first()
        if product is None:
            product = Product(**product_data)
            db.add(product)
            db.flush()
        products[product.sku] = product

    competitors: dict[str, Competitor] = {}
    for competitor_data in DEMO_COMPETITORS:
        competitor = (
            db.query(Competitor)
            .filter(Competitor.name == competitor_data["name"])
            .first()
        )
        if competitor is None:
            competitor = Competitor(**competitor_data)
            db.add(competitor)
            db.flush()
        competitors[competitor.name] = competitor

    for product in products.values():
        exists = db.query(CostProfile).filter(CostProfile.product_id == product.id).first()
        if exists is None:
            db.add(
                CostProfile(
                    product_id=product.id,
                    material_cost=1200.0 if "FLYER" in product.sku else 400.0,
                    labor_cost=700.0 if "FLYER" in product.sku else 250.0,
                    overhead_cost=300.0 if "FLYER" in product.sku else 120.0,
                    target_margin_rate=0.35,
                )
            )

    first_product = products["DEMO-A3-FLYER"]
    second_product = products["DEMO-BRAND-STICKER"]
    for competitor in competitors.values():
        exists = (
            db.query(CompetitorPrice)
            .filter(
                CompetitorPrice.competitor_id == competitor.id,
                CompetitorPrice.product_id == first_product.id,
            )
            .first()
        )
        if exists is None:
            db.add(
                CompetitorPrice(
                    competitor_id=competitor.id,
                    product_id=first_product.id,
                    reference_price=52000.0,
                    source_note="Demo-only manual reference. Not real market data.",
                    observed_at=datetime(2026, 1, 1),
                )
            )

    draft_table = (
        db.query(PriceTable)
        .filter(PriceTable.name == "Demo Draft Price Table")
        .first()
    )
    if draft_table is None:
        draft_table = PriceTable(
            name="Demo Draft Price Table",
            status="draft",
            description="Demo-only draft table for API testing.",
        )
        db.add(draft_table)
        db.flush()

    active_table = (
        db.query(PriceTable)
        .filter(PriceTable.name == "Demo Active Price Table")
        .first()
    )
    if active_table is None:
        active_table = PriceTable(
            name="Demo Active Price Table",
            status="active",
            description="Demo-only active table for API testing. Not generated by AI.",
        )
        db.add(active_table)
        db.flush()

    _ensure_price_item(db, draft_table.id, first_product.id, 55000.0, 0.36)
    _ensure_price_item(db, draft_table.id, second_product.id, 18000.0, 0.34)
    _ensure_price_item(db, active_table.id, first_product.id, 59000.0, 0.39)
    _ensure_price_item(db, active_table.id, second_product.id, 21000.0, 0.37)


def _ensure_price_item(
    db: Session,
    price_table_id: int,
    product_id: int,
    price: float,
    margin_rate: float,
) -> None:
    exists = (
        db.query(PriceTableItem)
        .filter(
            PriceTableItem.price_table_id == price_table_id,
            PriceTableItem.product_id == product_id,
        )
        .first()
    )
    if exists is None:
        db.add(
            PriceTableItem(
                price_table_id=price_table_id,
                product_id=product_id,
                price=price,
                margin_rate=margin_rate,
            )
        )
