import sys
from pathlib import Path

from fastapi.testclient import TestClient

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from backend.db import create_db_and_tables
from backend.main import app
from backend.seed import seed_demo_data


client = TestClient(app)


def setup_module():
    create_db_and_tables()
    seed_demo_data()


def test_concise_explanation_from_direct_pricing_fields():
    response = client.post("/api/explanations/quote", json=_direct_payload())

    assert response.status_code == 200
    data = response.json()
    assert data["product_id"] == 1
    assert data["product_name"] == "Demo A3 Flyer"
    assert data["explanation_source"] == "deterministic_template"
    assert "financially safe" in data["explanation_summary"]
    assert "No price was generated by AI." in data["decision_boundaries"]


def test_manager_explanation_from_direct_pricing_fields():
    payload = _direct_payload()
    payload["explanation_style"] = "manager"
    payload["explanation_audience"] = "manager"
    response = client.post("/api/explanations/quote", json=payload)

    assert response.status_code == 200
    bullets = response.json()["explanation_bullets"]
    assert any("manager should confirm" in bullet for bullet in bullets)
    assert any("manager audience" in bullet for bullet in bullets)


def test_explanation_missing_product_returns_404():
    payload = _direct_payload()
    payload["product_id"] = 999999
    response = client.post("/api/explanations/quote", json=payload)

    assert response.status_code == 404


def test_explanation_rejects_invalid_quantity():
    payload = _direct_payload()
    payload["quantity"] = 0
    response = client.post("/api/explanations/quote", json=payload)

    assert response.status_code == 400


def test_explanation_rejects_invalid_proposed_price():
    payload = _direct_payload()
    payload["proposed_unit_price"] = 0
    response = client.post("/api/explanations/quote", json=payload)

    assert response.status_code == 400


def test_explanation_rejects_invalid_validation_status():
    payload = _direct_payload()
    payload["validation_status"] = "unknown"
    response = client.post("/api/explanations/quote", json=payload)

    assert response.status_code == 400


def test_explanation_rejects_invalid_risk_level():
    payload = _direct_payload()
    payload["risk_level"] = "unknown"
    response = client.post("/api/explanations/quote", json=payload)

    assert response.status_code == 400


def test_explanation_states_no_approval_or_activation():
    response = client.post("/api/explanations/quote", json=_direct_payload())

    assert response.status_code == 200
    data = response.json()
    combined_text = " ".join(data["explanation_bullets"] + data["decision_boundaries"])
    assert "does not approve or activate" in combined_text
    assert "No approval decision was made by AI." in combined_text


def test_explanation_from_approval_request_snapshot():
    approval = client.post(
        "/api/approval-requests",
        json={
            "product_id": 1,
            "quantity": 10,
            "proposed_unit_price": 4000,
            "minimum_margin_rate": 0.3,
        },
    )
    assert approval.status_code == 201

    response = client.post(
        "/api/explanations/quote",
        json={
            "approval_request_id": approval.json()["id"],
            "explanation_style": "detailed",
        },
    )

    assert response.status_code == 200
    data = response.json()
    assert data["proposed_unit_price"] == 4000.0
    assert data["validation_status"] == "passed"
    assert data["risk_level"] == "low"


def test_openapi_includes_quote_explanation_path():
    response = client.get("/openapi.json")

    assert response.status_code == 200
    assert "/api/explanations/quote" in response.json()["paths"]


def _direct_payload():
    return {
        "product_id": 1,
        "quantity": 10,
        "unit_cost": 2200,
        "proposed_unit_price": 4000,
        "estimated_margin_rate": 0.45,
        "validation_status": "passed",
        "risk_level": "low",
        "explanation_audience": "manager",
        "explanation_style": "concise",
    }
