import sys
from pathlib import Path

from fastapi.testclient import TestClient

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from backend.db import create_db_and_tables
from backend.main import app
from backend.seed import seed_demo_data


client = TestClient(app)


def setup_module():
    create_db_and_tables()
    seed_demo_data()


def test_create_customer_quote_request_successfully():
    response = _create_request()

    assert response.status_code == 201
    data = response.json()
    assert data["customer_name"] == "Demo Customer"
    assert data["product_id"] == 1
    assert data["product_name"] == "Demo A3 Flyer"
    assert data["quantity"] == 25
    assert data["status"] == "new"
    assert "No price was generated by AI." in data["workflow_notes"]


def test_list_customer_quote_requests():
    created = _create_request().json()
    response = client.get("/api/customer-quote-requests", headers=_auth_headers("viewer"))

    assert response.status_code == 200
    assert any(item["id"] == created["id"] for item in response.json())


def test_get_quote_request_by_id():
    created = _create_request().json()
    response = client.get(
        f"/api/customer-quote-requests/{created['id']}",
        headers=_auth_headers("viewer"),
    )

    assert response.status_code == 200
    assert response.json()["id"] == created["id"]


def test_update_quote_request_status():
    created = _create_request().json()
    response = client.post(
        f"/api/customer-quote-requests/{created['id']}/status",
        headers=_auth_headers("manager"),
        json={
            "status": "reviewing",
            "assigned_to_username": "manager",
            "internal_note": "Reviewing cost profile and candidate prices.",
        },
    )

    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "reviewing"
    assert data["assigned_to_username"] == "manager"
    assert data["internal_note"] == "Reviewing cost profile and candidate prices."
    assert data["reviewed_at"] is not None


def test_invalid_quantity_returns_error():
    response = _create_request(quantity=0)

    assert response.status_code == 400


def test_missing_product_returns_404():
    response = _create_request(product_id=999999)

    assert response.status_code == 404


def test_quote_preview_from_request_works():
    created = _create_request().json()
    response = client.post(
        f"/api/customer-quote-requests/{created['id']}/quote-preview",
        headers=_auth_headers("manager"),
    )

    assert response.status_code == 200
    data = response.json()
    assert data["product_id"] == 1
    assert data["quantity"] == 25
    assert data["suggested_unit_price"] == 3384.62


def test_candidate_prices_from_request_works():
    created = _create_request().json()
    response = client.post(
        f"/api/customer-quote-requests/{created['id']}/candidate-prices",
        headers=_auth_headers("manager"),
        json={"margin_rates": [0.25, 0.35], "include_competitor_context": True},
    )

    assert response.status_code == 200
    data = response.json()
    assert data["product_id"] == 1
    assert data["quantity"] == 25
    assert len(data["candidates"]) == 2
    assert data["competitor_context"]["reference_price_count"] == 2


def test_audit_log_is_created_after_request_creation():
    created = _create_request().json()
    response = client.get(
        "/api/audit-logs",
        params={"action": "customer_quote_request_created", "limit": 1},
        headers=_auth_headers("admin"),
    )

    assert response.status_code == 200
    log = response.json()[0]
    assert log["entity_id"] == str(created["id"])
    assert '"quantity":25' in log["metadata_json"]


def test_audit_log_is_created_after_status_change():
    created = _create_request().json()
    client.post(
        f"/api/customer-quote-requests/{created['id']}/status",
        headers=_auth_headers("manager"),
        json={"status": "quoted", "assigned_to_username": "manager"},
    )
    response = client.get(
        "/api/audit-logs",
        params={"action": "customer_quote_request_status_changed", "limit": 1},
        headers=_auth_headers("admin"),
    )

    assert response.status_code == 200
    log = response.json()[0]
    assert log["entity_id"] == str(created["id"])
    assert '"status":"quoted"' in log["metadata_json"]


def test_openapi_includes_customer_quote_requests_path():
    response = client.get("/openapi.json")

    assert response.status_code == 200
    paths = response.json()["paths"]
    assert "/api/customer-quote-requests" in paths
    assert "/api/customer-quote-requests/{request_id}" in paths
    assert "/api/customer-quote-requests/{request_id}/status" in paths
    assert "/api/customer-quote-requests/{request_id}/quote-preview" in paths
    assert "/api/customer-quote-requests/{request_id}/candidate-prices" in paths


def _create_request(product_id: int = 1, quantity: int = 25):
    return client.post(
        "/api/customer-quote-requests",
        json={
            "customer_name": "Demo Customer",
            "customer_email": "customer@example.com",
            "customer_company": "Demo Company",
            "product_id": product_id,
            "quantity": quantity,
            "requested_due_date": "2026-02-01T00:00:00",
            "request_note": "Please provide a quote for 25 units.",
        },
    )


def _auth_headers(username: str) -> dict:
    token = _login(username, f"{username}-demo-password")
    return {"Authorization": f"Bearer {token}"}


def _login(username: str, password: str) -> str:
    response = client.post("/api/auth/login", json={"username": username, "password": password})
    assert response.status_code == 200
    return response.json()["access_token"]
